passportxyz/id-staking-v2-app

app/package.json, app/src/abi/IdentityStaking.json, app/src/components/DoneToastContent.tsx, app/src/components/ManageAccountCenter.tsx, app/src/components/MinimalHeader.tsx, app/src/components/components_staking/RestakeButton.tsx, app/src/components/components_staking/YourStakeHistory.tsx, app/yarn.lock
fixes https://github.com/gitcoinco/passport/issues/2212
=> feat(app): working restaking

app/src/components/components_staking/NetworkDropdown.tsx, app/src/components/components_staking/YourStakeForm.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2211
=> fix: build errors

app/src/components/components_staking/NetworkDropdown.tsx, app/src/components/components_staking/StakeModal.tsx, app/src/components/components_staking/YourStakeForm.tsx, app/src/utils/chains.ts
This fixes [2210](https://github.com/gitcoinco/passport/issues/2211)
=> 2210 stake

app/src/components/MinimalHeader.tsx, app/src/components/components_staking/LoggedInPageRoot.tsx, app/src/pages/faq.tsx, app/src/pages/home.tsx, app/src/pages/leaderboard.tsx, app/src/pages/signin.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2210
=> 2210 fix sign in

app/src/components/components_staking/NetworkDropdown.tsx, app/src/components/components_staking/YourStakeHistory.tsx, app/src/utils/stakeHistory.ts
fixes https://github.com/gitcoinco/passport/issues/2212
=> feat(ui): filter stake history using the chain ID

app/src/components/components_staking/OnOthersUpdateButton.tsx, app/src/components/components_staking/StakeForOthers.tsx, app/src/components/components_staking/StakeForOthersHistory.tsx, app/src/components/components_staking/StakeSection.tsx, app/src/pages/home.tsx
=> 2289 history component

app/src/components/SIWEButton.tsx, app/src/components/components_staking/PlatformCard.tsx, app/src/pages/signin.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2208
=> 2208 connect wallet

app/public/assets/vertical-submenu.svg, app/src/components/components_staking/CommunityRestakeModal.tsx, app/src/components/components_staking/CommunityUnstakeModal.tsx, app/src/components/components_staking/CommunityUpdateButton.tsx, app/src/components/components_staking/StakeForOthersForm.tsx, app/src/components/components_staking/StakeForOthersHistory.tsx, app/src/utils/helpers.tsx
This fixes https://github.com/gitcoinco/passport/issues/2289
=> WIP restake & unstake modal

app/src/components/Header.tsx, app/src/components/MinimalHeader.tsx, app/src/components/components_staking/PageRoot.tsx, app/src/pages/index.tsx, app/src/pages/terms.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2307
=> Adding terms page

app/src/pages/terms.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2307
=> Fixing build errors

app/src/abi/IdentityStaking.json, app/src/components/components_staking/CommunityRestakeModal.tsx, app/src/components/components_staking/CommunityUnstakeModal.tsx, app/src/components/components_staking/CommunityUpdateButton.tsx, app/src/components/components_staking/SelfRestakeModal.tsx, app/src/components/components_staking/SelfStakeModal.tsx, app/src/components/components_staking/SelfUnstakeModal.tsx, app/src/components/components_staking/StakeForOthers.tsx, app/src/components/components_staking/StakeForOthersForm.tsx, app/src/components/components_staking/StakeForOthersHistory.tsx, app/src/components/components_staking/StakeForOthersModal.tsx, app/src/components/components_staking/StakeModal.tsx, app/src/components/components_staking/YourStakeForm.tsx, app/src/components/components_staking/YourStakeHistory.tsx, app/src/hooks/hooks_staking/useStakeTxHandler.tsx, app/src/hooks/hooks_staking/useStakeTxWithApprovalCheck.tsx, app/src/utils/stakeHistory.ts
fixes https://github.com/gitcoinco/passport/issues/2288
=> feat(ui): adding c-stake modal, updating c-stake form

app/src/components/components_staking/CommunityUpdateButton.tsx, app/src/components/components_staking/SelfStakeModal.tsx, app/src/components/components_staking/StakeForOthersHistory.tsx, app/src/components/components_staking/StakeFormInputSection.tsx, app/src/components/components_staking/StakeSection.tsx, app/src/components/components_staking/YourStakeForm.tsx, app/src/hooks/hooks_staking/useStakeTxWithApprovalCheck.tsx, app/src/styles/globals.css, app/src/utils/stakeHistory.ts
fixes https://github.com/gitcoinco/passport/issues/2290
=> feat(ui): working c-stake modals

app/src/components/components_staking/StakeForOthersHistory.tsx
this fixes https://github.com/gitcoinco/passport/issues/2289
=> update date format

app/src/components/components_staking/TosModal.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2306
=> Changing link to tos point

app/src/components/components_staking/TosModal.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2306
=> Updating terms text

app/src/components/components_staking/TosModal.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2290
=> Updating title for terms

app/src/utils/stakeHistory.ts
this fixes https://github.com/gitcoinco/passport/issues/2310
=> update api returned data

app/src/utils/stakeHistory.ts
This fixes https://github.com/gitcoinco/passport/issues/2367
=> modify the stake history to process the new data

app/src/components/components_staking/CommunityUpdateButton.tsx, app/src/components/components_staking/StakeForOthersHistory.tsx, app/src/hooks/legacyStaking.tsx
fixes https://github.com/gitcoinco/passport/issues/2051
=> fix: build fix

app/src/components/Button.tsx, app/src/components/PasswordPage.tsx, app/src/components/components_staking/CommunityUpdateButton.tsx, app/src/components/components_staking/StakeForOthersForm.tsx, app/src/components/components_staking/StakeFormInputSection.tsx, app/src/components/components_staking/StakeSection.tsx, app/src/components/components_staking/YourStakeForm.tsx, app/src/utils/theme/palette.tsx, app/src/utils/theme/setTheme.tsx, app/src/utils/theme/themes.tsx, app/src/utils/theme/types.tsx, app/tailwind.config.ts
- add transition to hover for buttons, also buttons are now solid colors instead of gradients
- increase button & input sizes in the stake forms
- remove orange online for inputs
fixes: https://github.com/gitcoinco/passport/issues/2325
=> feat: UI improvements

app/package.json, app/src/pages/faq.tsx, app/src/pages/terms.tsx, app/yarn.lock
fixes https://github.com/gitcoinco/passport/issues/2418
=> feat(app): updating terms of service

app/src/components/Button.tsx, app/src/components/components_staking/NetworkDropdown.tsx, app/src/components/components_staking/StakeFormInputSection.tsx, app/src/components/components_staking/StakeSection.tsx, app/src/pages/faq.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2325
=> feat: keep the opacity of the home page section at 100 if it is open

app/src/pages/signin.tsx
This fixes https://github.com/gitcoinco/passport/issues/2502
=> update landing page text

app/src/components/components_staking/NetworkDropdown.tsx, app/src/hooks/useSupportBanners.tsx
This fixes https://github.com/gitcoinco/passport/issues/2516
=> display text for chain select & modify banners endpoint

app/src/components/components_staking/TosModal.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2504
=> feat: updating tos

app/src/context/datastoreConnectionContext.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2519
=> fate: using watchAccount to watch for account disconnect

app/src/components/components_staking/TosModal.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2504
=> feat: styling links in the TOS Modal

app/src/components/Header.tsx, app/src/components/MinimalHeader.tsx, app/src/components/components_staking/LoggedInPageRoot.tsx, app/src/components/components_staking/PageRoot.tsx, app/src/pages/faq.tsx
fixes https://github.com/gitcoinco/passport/issues/2550
=> feat(app): allowing access to faq without login

app/src/components/components_staking/StakeForOthersForm.tsx
fixes https://github.com/gitcoinco/passport/issues/2526
=> feat(app): alert user about stakee input errors

app/src/components/components_staking/Footer.tsx
This fixes https://github.com/gitcoinco/passport/issues/2646
=> add z index to footer

.github/workflows/deploy_infra.yml
fixes https://github.com/passportxyz/passport/issues/2808
=> feat(infra): updating pulumi org name

infra/package.json, infra/yarn.lock
This fixes https://github.com/passportxyz/core-infra/issues/71
=> add fixed version for infra lib

.github/workflows/deploy_infra.yml
this fixes https://github.com/passportxyz/passport/issues/3323
=> modify source secret for aws credentials

.github/workflows/release_and_deploy.yml, .github/workflows/sync_to_s3_generic_build_staking_app.yml, .github/workflows/sync_to_s3_generic_push_staking_app.yml
Fixes: https://github.com/passportxyz/passport/issues/3371
=> feat: deploy app to s3

.github/workflows/deploy_infra.yml, .github/workflows/deploy_ui_generic.yml, .github/workflows/sync_to_s3_generic_build_staking_app.yml, .github/workflows/sync_to_s3_generic_push_staking_app.yml, app/next.config.mjs
Fixes: https://github.com/passportxyz/passport/issues/3371
=> fix: 'cache-dependency-path: app/yarn.lock'
